apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nhzgte0k2-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:e0da660aa12577aa3fca01ea76b6cb90d0e86728@sha256:6407ac1b402cd896378e3f1e1f4fe4c6e9040d047b7b5da2a344f3082c82a019
          name: container-image
